workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
    scripts:
      - name: Update iOS deployment target in Podfile
        script: |
          sed -i '' "s/platform :ios, .*/platform :ios, '15.0'/" ios/Podfile
      
      - name: Clean project
        script: |
          flutter clean
          cd ios && rm -rf Pods Podfile.lock && cd ..
      
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      
      - name: Build iOS release
        script: flutter build ipa --release
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true